### ISSUE TITLE
Find best language for instructions and tutorials

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/project-iiif-annotate#11]
Foe example, re identify (mark up), transcribe (fine?), annotate (mark and type) - use most precise language possible without jargon

**Comment by mialondon** [comment]
I've been trying to think of a better description than '"Select an area of the image"' for the tutorial, but I've gotten stuck on device-neutral language e.g. click and drag your mouse presumably doesn't work for tablets.

**Comment by alexandermendes** [comment]
Yep I thought exactly the same thing about the mouse/tablet issue - "Click and drag with your mouse (or touch and move with your finger)..." does get a bit long. It should hopefully be pretty intuitive anyway, with selecting areas being a pretty standard thing.

**Comment by alexandermendes** [comment]
Closing as this will really be an ongoing configuration issue, rather than one that will ever be fully 'solved'.

**Comment by mialondon** [comment]
If we're using github to manage deliverables then we need it on the list - I'll assign it to me so it doesn't bother you.

**Comment by alexandermendes** [comment]
Ok, I suppose the point was that it will always be a permanent item on the list! But that's fine of course, we can leave it here.

**Comment by mialondon** [comment]
Useful images in https://github.com/LibCrowds/vue-pybossa-frontend/issues/183

**Comment by alexandermendes** [comment]
This repo will be gone soon as we move to a new way of generating projects via the interface, I think we may as well close this as there's nothing to directly solve
