### ISSUE TITLE
Refreshing browser and saving tasks completed

### ISSUE THREAD

**Issue by christianalgar** [LibCrowds/project-iiif-annotate#46]
I think I've come across a problem whereby submitted tasks may be lost if a user refreshes the page? I lost a good many completed tasks having pressed the reload button.
Does anyone think people may be looking for a button to say something to the effect of, 'i'm done for now', or 'i'll be back later'? Currently, there doesn't appear to be a way for a user to know how to sign-off and be sure that there efforts have been saved?

**Comment by alexandermendes** [comment]
The task page will only load tasks that you haven't previously completed, so if you refresh it is expected that they will disappear. It is confusing and I'm hoping a few of the upcoming changes will help make things clearer but don't worry, you haven't lost any work!

I think this might be another example of the browse functionality confusing things a bit. It falsely gives the impression that the user is free to move back and forth between tasks/images but really we're dealing with a queue based system where each task can only be completed once.

I have just removed this browse function from our staging server (should be made live on Monday), so now the task page now only shows you the next uncompleted task and when you click save it just moves to the next. We'll then have a separate area where users are free to browse all pages in a volume, see and (the bit I'm most looking forward to) search all annotations - this may be a few weeks off but we'll get there!

**Comment by christianalgar** [comment]
I'm probably doing something wrong, but it doesn't seem to be saving tasks I've done. My stats and the percentage of the volume completed aren't changing - it's been 36% for ages.

**Comment by christianalgar** [comment]
I'm getting playbills I've already done. 
![image](https://user-images.githubusercontent.com/29711355/30514945-32095a56-9b17-11e7-86a0-b3e58041fb63.png)

**Comment by alexandermendes** [comment]
I think this is probably you: https://www.libcrowds.com/account/christian

So your contribution count on the left is going up (but I think that updates every 15 mins or so).

The overall progress for the project won't go up straight away as we need 3 contributions per task and at the moment it's just calculated by *completed_tasks / total_tasks x 100*. But this is a good point, it should really be calculated by *answers / (total_tasks x required_answers) x 100*. This will require some changes to the core PyBossa backend but I think it should be done. I'll handle that in a separate issue (here https://github.com/LibCrowds/vue-pybossa-frontend/issues/276).

**Comment by alexandermendes** [comment]
Not sure about the playbills being presented again once already done, that really shouldn't happen. Could you click 'Copy Image URL' and paste that in here if you encounter it again? Thanks.

**Comment by christianalgar** [comment]
Will do, the 'repeat' playbill disappears once press reload and get new playbills, but this could confuse people (like me, but I am easily confused! Thanks. Have a good weekend : )

**Comment by christianalgar** [comment]
ok - whilst i'm still at this - http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=268 this one I have already done but has reappeared when I returned to the volume after doing some of the other volume.

**Comment by alexandermendes** [comment]
Ok, so let's revisit this once the method of loading/browsing tasks is updated next week. Hopefully some of this will naturally become a bit clearer then. I agree that it is a bit confusing as it is!

**Comment by alexandermendes** [comment]
Hopefully this one should be solved now!
